# config/packages/security.yaml
security:
    # 1) Hashage des mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # 2) Chargement des utilisateurs depuis l'entité User
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 3) Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # 3.1. FORM LOGIN — affiche le formulaire sur GET /login et traite le POST sur /login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true

            # 3.2. LOGOUT — Symfony supprime la session sur /logout et redirige ensuite
            logout:
                path: app_logout           # doit correspondre à #[Route(path:'/logout', name:'logout')]
                target: app_home
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 semaine      

            provider: app_user_provider

    # 4) Contrôle d’accès (order = important !) 
    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/verify, roles: PUBLIC_ACCESS }


when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
